In [ ]:
import torch

In [2]:
a = torch.randn(3, 4)
b = torch.randn(3, 4)
a, b

(tensor([[ 0.6727, -0.9816, -1.2440,  1.0890],
         [ 1.0834,  0.9684, -0.0776,  1.3015],
         [ 0.9677,  0.0419,  2.8440, -0.1337]]),
 tensor([[ 0.0064, -0.2101, -0.6011,  0.0967],
         [ 0.7047,  0.0066,  0.3915, -0.2608],
         [-0.4947, -1.0237,  1.9989,  0.6699]]))

In [5]:
a = torch.randn(5, 3, 3)
a.inverse() @ a

tensor([[[ 1.0000e+00, -9.3132e-09, -4.4703e-08],
         [ 0.0000e+00,  1.0000e+00,  1.1921e-07],
         [ 5.9605e-08, -1.0431e-07,  1.0000e+00]],

        [[ 1.0000e+00,  8.5682e-08,  0.0000e+00],
         [ 1.4901e-08,  1.0000e+00, -1.4901e-08],
         [ 2.3842e-07,  1.7881e-07,  1.0000e+00]],

        [[ 1.0000e+00,  2.9802e-08,  2.9802e-08],
         [ 5.9605e-08,  1.0000e+00,  1.4901e-08],
         [ 0.0000e+00,  0.0000e+00,  1.0000e+00]],

        [[ 1.0000e+00,  0.0000e+00,  1.1921e-07],
         [ 4.7684e-07,  1.0000e+00,  0.0000e+00],
         [-2.3842e-07,  1.1921e-07,  1.0000e+00]],

        [[ 1.0000e+00,  0.0000e+00,  5.9605e-08],
         [-4.1910e-09,  1.0000e+00,  3.7253e-09],
         [ 0.0000e+00,  0.0000e+00,  1.0000e+00]]])

In [3]:
torch.cross(a, b, dim=0)


tensor([[-1.6103, -0.3254, -1.4760,  0.6997],
        [-0.8191, -0.9591,  2.1283, -0.4932],
        [ 2.3322, -0.9330, -1.4794, -1.2804]])

In [4]:
torch.tensor([[0.0]]).repeat(10, 2)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [5]:
b1 = torch.rand(16, 5)
b2 = torch.rand(8, 5)
b1.shape, b2.shape


(torch.Size([16, 5]), torch.Size([8, 5]))

In [6]:
b1.split(1)

(tensor([[0.8206, 0.8191, 0.8330, 0.0551, 0.3871]]),
 tensor([[0.5685, 0.7462, 0.0359, 0.2181, 0.9472]]),
 tensor([[0.5930, 0.1087, 0.1438, 0.0105, 0.6199]]),
 tensor([[0.6408, 0.2193, 0.9154, 0.1773, 0.4620]]),
 tensor([[0.8749, 0.4552, 0.3843, 0.0494, 0.7655]]),
 tensor([[0.9682, 0.9208, 0.3082, 0.1671, 0.1007]]),
 tensor([[0.1343, 0.7050, 0.3858, 0.4155, 0.3796]]),
 tensor([[0.1014, 0.8620, 0.0015, 0.6411, 0.6728]]),
 tensor([[0.7612, 0.2291, 0.9714, 0.6113, 0.0071]]),
 tensor([[0.9755, 0.3452, 0.1330, 0.4663, 0.1182]]),
 tensor([[0.1740, 0.1860, 0.0108, 0.4562, 0.1686]]),
 tensor([[0.6790, 0.9188, 0.7956, 0.5086, 0.2325]]),
 tensor([[0.8378, 0.3986, 0.7167, 0.7230, 0.9768]]),
 tensor([[0.6681, 0.0760, 0.4104, 0.6122, 0.7601]]),
 tensor([[0.6991, 0.0112, 0.8521, 0.3473, 0.5815]]),
 tensor([[0.8399, 0.3688, 0.4499, 0.7874, 0.9305]]))

In [7]:
b1_ids = torch.tensor([])


In [8]:
x = torch.arange(2*3*16*16).reshape((2, 3, 16, 16))  # (B, C, H, W)

In [9]:
x

tensor([[[[   0,    1,    2,  ...,   13,   14,   15],
          [  16,   17,   18,  ...,   29,   30,   31],
          [  32,   33,   34,  ...,   45,   46,   47],
          ...,
          [ 208,  209,  210,  ...,  221,  222,  223],
          [ 224,  225,  226,  ...,  237,  238,  239],
          [ 240,  241,  242,  ...,  253,  254,  255]],

         [[ 256,  257,  258,  ...,  269,  270,  271],
          [ 272,  273,  274,  ...,  285,  286,  287],
          [ 288,  289,  290,  ...,  301,  302,  303],
          ...,
          [ 464,  465,  466,  ...,  477,  478,  479],
          [ 480,  481,  482,  ...,  493,  494,  495],
          [ 496,  497,  498,  ...,  509,  510,  511]],

         [[ 512,  513,  514,  ...,  525,  526,  527],
          [ 528,  529,  530,  ...,  541,  542,  543],
          [ 544,  545,  546,  ...,  557,  558,  559],
          ...,
          [ 720,  721,  722,  ...,  733,  734,  735],
          [ 736,  737,  738,  ...,  749,  750,  751],
          [ 752,  753,  754,  ...

In [10]:
x.shape[1::-1]

torch.Size([3, 2])

In [11]:
torch.equal(x, x.unfold(2, 4, 4).unfold(3, 4, 4).permute(0, 1, 2, 4, 3, 5).reshape((2, 3, 16, 16)))


True

In [12]:
i, j = 0, 0
x.unfold(2, 4, 4).unfold(3, 4, 4)[:, :, i, j, :, :].shape


torch.Size([2, 3, 4, 4])

In [13]:
x.unfold(2, 2, 2).unfold(3, 2, 2).permute(0, 2, 3, 4, 5, 1).flatten(3, 5).flatten(1, 2).shape

torch.Size([2, 64, 12])

In [14]:
x.unfold(2, 4, 4).unfold(3, 4, 4)[:, :, i, j, :, :], x[:, :, i*4:i*4+4, j*4:j*4+4]

(tensor([[[[   0,    1,    2,    3],
           [  16,   17,   18,   19],
           [  32,   33,   34,   35],
           [  48,   49,   50,   51]],
 
          [[ 256,  257,  258,  259],
           [ 272,  273,  274,  275],
           [ 288,  289,  290,  291],
           [ 304,  305,  306,  307]],
 
          [[ 512,  513,  514,  515],
           [ 528,  529,  530,  531],
           [ 544,  545,  546,  547],
           [ 560,  561,  562,  563]]],
 
 
         [[[ 768,  769,  770,  771],
           [ 784,  785,  786,  787],
           [ 800,  801,  802,  803],
           [ 816,  817,  818,  819]],
 
          [[1024, 1025, 1026, 1027],
           [1040, 1041, 1042, 1043],
           [1056, 1057, 1058, 1059],
           [1072, 1073, 1074, 1075]],
 
          [[1280, 1281, 1282, 1283],
           [1296, 1297, 1298, 1299],
           [1312, 1313, 1314, 1315],
           [1328, 1329, 1330, 1331]]]]),
 tensor([[[[   0,    1,    2,    3],
           [  16,   17,   18,   19],
           [  32

In [15]:
x.unfold(2, 4, 4).unfold(3, 4, 4)[:, :, 0, 0, :, :]

tensor([[[[   0,    1,    2,    3],
          [  16,   17,   18,   19],
          [  32,   33,   34,   35],
          [  48,   49,   50,   51]],

         [[ 256,  257,  258,  259],
          [ 272,  273,  274,  275],
          [ 288,  289,  290,  291],
          [ 304,  305,  306,  307]],

         [[ 512,  513,  514,  515],
          [ 528,  529,  530,  531],
          [ 544,  545,  546,  547],
          [ 560,  561,  562,  563]]],


        [[[ 768,  769,  770,  771],
          [ 784,  785,  786,  787],
          [ 800,  801,  802,  803],
          [ 816,  817,  818,  819]],

         [[1024, 1025, 1026, 1027],
          [1040, 1041, 1042, 1043],
          [1056, 1057, 1058, 1059],
          [1072, 1073, 1074, 1075]],

         [[1280, 1281, 1282, 1283],
          [1296, 1297, 1298, 1299],
          [1312, 1313, 1314, 1315],
          [1328, 1329, 1330, 1331]]]])

In [16]:
x.unfold(2, 4, 4).unfold(3, 4, 4).permute(0, 2, 3, 4, 5, 1)

tensor([[[[[[   0,  256,  512],
            [   1,  257,  513],
            [   2,  258,  514],
            [   3,  259,  515]],

           [[  16,  272,  528],
            [  17,  273,  529],
            [  18,  274,  530],
            [  19,  275,  531]],

           [[  32,  288,  544],
            [  33,  289,  545],
            [  34,  290,  546],
            [  35,  291,  547]],

           [[  48,  304,  560],
            [  49,  305,  561],
            [  50,  306,  562],
            [  51,  307,  563]]],


          [[[   4,  260,  516],
            [   5,  261,  517],
            [   6,  262,  518],
            [   7,  263,  519]],

           [[  20,  276,  532],
            [  21,  277,  533],
            [  22,  278,  534],
            [  23,  279,  535]],

           [[  36,  292,  548],
            [  37,  293,  549],
            [  38,  294,  550],
            [  39,  295,  551]],

           [[  52,  308,  564],
            [  53,  309,  565],
            [  54,  310,

In [17]:
x.unfold(1, 3,1)

tensor([[[[[   0,  256,  512],
           [   1,  257,  513],
           [   2,  258,  514],
           ...,
           [  13,  269,  525],
           [  14,  270,  526],
           [  15,  271,  527]],

          [[  16,  272,  528],
           [  17,  273,  529],
           [  18,  274,  530],
           ...,
           [  29,  285,  541],
           [  30,  286,  542],
           [  31,  287,  543]],

          [[  32,  288,  544],
           [  33,  289,  545],
           [  34,  290,  546],
           ...,
           [  45,  301,  557],
           [  46,  302,  558],
           [  47,  303,  559]],

          ...,

          [[ 208,  464,  720],
           [ 209,  465,  721],
           [ 210,  466,  722],
           ...,
           [ 221,  477,  733],
           [ 222,  478,  734],
           [ 223,  479,  735]],

          [[ 224,  480,  736],
           [ 225,  481,  737],
           [ 226,  482,  738],
           ...,
           [ 237,  493,  749],
           [ 238,  494,  750

In [18]:
a = torch.rand((4, 8, 20, 20))[1, :, :4, :4]

In [1]:
import torch

In [18]:
X = torch.zeros(10, 1, 1, 30, 30)
Y = torch.zeros(10, 1, 1, 30, 30)
X.shape

torch.Size([10, 1, 1, 30, 30])

In [19]:
X = X.squeeze()
Y = Y.squeeze()

In [20]:
X.shape, Y.shape

(torch.Size([10, 30, 30]), torch.Size([10, 30, 30]))

In [29]:
torch.stack([torch.zeros(3), torch.zeros(3)], dim = 0)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [4]:
einops.einsum(torch.arange(9).reshape((3, 3)), torch.arange(9).reshape((3, 3)), 'c0 c1, c1 c2 -> c0 c2')

tensor([[ 15,  18,  21],
        [ 42,  54,  66],
        [ 69,  90, 111]])

In [ ]:
einops.einsum(torch.arange(9).reshape((3, 3)), torch.arange(9).reshape((3, 3)), 'c0 c1, c1 c2 -> c0 c2')

In [93]:
a = torch.nn.Sequential(
    torch.nn.LazyLinear(10),
    torch.nn.LazyBatchNorm1d(),
    torch.nn.ReLU(),
    torch.nn.LazyLinear(20),
    torch.nn.ReLU(),
    torch.nn.LazyLinear(10)
)

In [72]:
a[0]

Linear(in_features=4, out_features=10, bias=True)

In [94]:
a(torch.rand(size=(4, 4)))

tensor([[-0.4615, -0.0262,  0.0428, -0.5188,  0.0120, -0.0856, -0.3297,  0.1843,
          0.1498, -0.0764],
        [-0.2198,  0.0135, -0.0677, -0.2538,  0.2016, -0.0811, -0.1293,  0.2910,
         -0.1445, -0.1108],
        [-0.3123, -0.0331,  0.0099, -0.4146,  0.0722, -0.0846, -0.2697,  0.2257,
         -0.0032, -0.1253],
        [-0.3668, -0.1133, -0.1058, -0.3134,  0.1531,  0.1107, -0.0675,  0.3069,
          0.1053, -0.1531]], grad_fn=<AddmmBackward0>)

In [96]:
list(a.named_parameters())

[('0.weight',
  Parameter containing:
  tensor([[-0.2118, -0.4052, -0.0595,  0.3990],
          [ 0.4234,  0.1790,  0.0345, -0.2041],
          [-0.3510, -0.3326,  0.4467,  0.0475],
          [ 0.3226,  0.0363,  0.3021, -0.0989],
          [ 0.2453,  0.4401, -0.1271,  0.4927],
          [-0.1943,  0.3300,  0.4968,  0.0832],
          [ 0.1133,  0.3985,  0.4881, -0.1086],
          [ 0.0448,  0.3627,  0.3610, -0.1468],
          [-0.4326, -0.0636,  0.0474, -0.2443],
          [-0.1734,  0.3181,  0.0250, -0.1766]], requires_grad=True)),
 ('0.bias',
  Parameter containing:
  tensor([-0.2559, -0.0250, -0.3494,  0.2855,  0.3095, -0.3576, -0.2403,  0.2026,
           0.0536, -0.2111], requires_grad=True)),
 ('1.weight',
  Parameter containing:
  tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], requires_grad=True)),
 ('1.bias',
  Parameter containing:
  tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)),
 ('3.weight',
  Parameter containing:
  tensor([[-0.2901, -0.1901,  0.

In [84]:
list(a.parameters())[0].shape

torch.Size([10, 4])

In [ ]:
def get_weights_biases(model):
    weights = [p for p, n in model.named_parameters() if 'weights' in n]
    biases = [p for p, n in model.named_parameters() if 'biases' in n]

[('0.weight',
  Parameter containing:
  tensor([[ 0.3927,  0.2279, -0.0838, -0.0222],
          [-0.2085, -0.2864,  0.2334, -0.7256],
          [ 0.1223, -0.1182,  0.4281, -0.8118],
          [ 0.1334, -0.5304,  0.5955,  0.0758],
          [ 0.0048,  0.0472,  0.1792,  0.5709],
          [-0.0582,  0.1158,  0.3952, -0.4837],
          [ 0.0989,  0.0763,  0.3809, -0.1588],
          [-0.1128,  0.2568,  0.8622,  0.3923],
          [-0.1978, -0.3124,  0.3139, -0.8139],
          [-0.2863, -1.0354,  0.1700,  0.1094]], requires_grad=True)),
 ('0.bias',
  Parameter containing:
  tensor([-0.6944,  0.8954, -0.9170,  1.1807, -0.2604,  0.0329,  1.1596, -2.4910,
           0.4808,  0.8174], requires_grad=True)),
 ('2.weight',
  Parameter containing:
  tensor([[-0.2629, -0.2217, -0.2476, -0.1200,  0.2108, -0.0340, -0.0423,  0.0661,
            0.0519, -0.2579],
          [-0.0083, -0.2394, -0.3022,  0.0906,  0.3116, -0.0890, -0.0182, -0.1098,
           -0.2960,  0.2721],
          [-0.3084, -0.011

In [98]:
torch.nn.init.xavier_normal_(list(a.parameters())[0])

Parameter containing:
tensor([[-2.1348e-01,  3.0470e-03,  4.7324e-02, -2.0505e-02],
        [ 6.8981e-01,  8.3789e-02, -3.4641e-01,  2.7094e-01],
        [ 3.7535e-01,  8.7811e-02, -4.6310e-01, -1.1449e-01],
        [-1.4129e-01,  1.8666e-01, -3.5796e-01,  1.2088e-01],
        [-4.7623e-04,  4.0725e-02,  2.9589e-01,  6.4918e-01],
        [-5.0316e-01, -1.3720e-01, -4.7356e-01, -8.6647e-01],
        [ 2.2447e-01, -1.8603e-01, -3.3062e-01,  6.4957e-01],
        [ 4.0915e-02,  2.9792e-01,  3.8743e-01,  2.1581e-01],
        [-2.0067e-01, -1.2592e-01, -1.7983e-01, -2.2471e-02],
        [-8.9005e-01,  4.3333e-03,  4.7045e-01,  5.1368e-02]],
       requires_grad=True)

In [23]:
import json
import torch

with open('./panoptic-toolbox/160224_ultimatum1/calibration_160224_ultimatum1.json') as f:
    j = json.load(f)


FileNotFoundError: [Errno 2] No such file or directory: './panoptic-toolbox/160224_ultimatum1/calibration_160224_ultimatum1.json'

In [16]:
torch.arange(9).reshape((3,3)).inverse()

RuntimeError: linalg.inv: Expected a floating point or complex tensor as input. Got Long

In [ ]:
o = [-torch.tensor(i['R']).T @ torch.tensor(i['t']) for i in list(filter(lambda x: x['type'] == 'hd', j['cameras']))]
o
# right down forward (looking from the door towards the inside) (right-handed)
# identity rotation is looking from the door towards the inside

[tensor([[-271.2090],
         [-151.7850],
         [ -18.8425]]),
 tensor([[ 211.0760],
         [-312.4540],
         [ -10.3636]]),
 tensor([[ -44.1615],
         [-338.8820],
         [ 181.5670]]),
 tensor([[ 208.7710],
         [-151.0890],
         [ 178.0990]]),
 tensor([[ 158.8330],
         [-339.3970],
         [ 100.5450]]),
 tensor([[-103.5360],
         [-152.5280],
         [ 256.4890]]),
 tensor([[ -67.7901],
         [-339.4660],
         [-170.4220]]),
 tensor([[  77.1355],
         [-312.1330],
         [ 198.1750]]),
 tensor([[ -63.0111],
         [-152.7540],
         [-267.1390]]),
 tensor([[ 265.5900],
         [-118.2840],
         [  70.7366]]),
 tensor([[  55.5375],
         [-313.5860],
         [-202.4670]]),
 tensor([[-140.6200],
         [-239.6910],
         [-208.8510]]),
 tensor([[  -7.6229],
         [-239.2450],
         [ 255.2270]]),
 tensor([[-184.0950],
         [-339.3290],
         [  14.3756]]),
 tensor([[ 151.0870],
         [-120.3920],
    

In [27]:
list(torch.arange(50).reshape((-1, 5)))

[tensor([0, 1, 2, 3, 4]),
 tensor([5, 6, 7, 8, 9]),
 tensor([10, 11, 12, 13, 14]),
 tensor([15, 16, 17, 18, 19]),
 tensor([20, 21, 22, 23, 24]),
 tensor([25, 26, 27, 28, 29]),
 tensor([30, 31, 32, 33, 34]),
 tensor([35, 36, 37, 38, 39]),
 tensor([40, 41, 42, 43, 44]),
 tensor([45, 46, 47, 48, 49])]

In [6]:
torch.zeros((5, 5))[:, 3:].shape

torch.Size([5, 2])

In [ ]:
import open3d as o3d
from open3d.visualization import draw_plotly

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [5]:
cube_red = o3d.geometry.TriangleMesh.create_box(1, 1, 1)
cube_red.compute_vertex_normals()
cube_red.paint_uniform_color((1.0, 0.0, 0.0))
draw_plotly([cube_red])

In [2]:
import torch
import torch.nn.functional as F

In [9]:
[(16 - i) % 16 for i in [5, 16, 17, 0, 4, 31, 32, 35]]

[11, 0, 15, 0, 12, 1, 0, 13]

In [10]:
pad = (0, 0, 1, 2)
pp = torch.ones((4, 3))
p = F.pad(pp, pad)
ppp = p[pad[2]:p.shape[-2]-pad[3], pad[0]:p.shape[-1]-pad[1]]
torch.equal(ppp, pp)

True

In [5]:
a = torch.tensor([5.], requires_grad=True)
a2 = a * a + 3 * a
a2.backward()
a.grad

tensor([13.])

In [8]:
import torch
import xformers.ops as xops

xops.fmha.ALL_FW_OPS, xops.fmha.ALL_BW_OPS

([xformers.ops.fmha.cutlass.FwOp,
  xformers.ops.fmha.flash.FwOp,
  xformers.ops.fmha.flash3.FwOp,
  xformers.ops.fmha.triton_splitk.FwOp],
 [xformers.ops.fmha.cutlass.BwOp,
  xformers.ops.fmha.flash.BwOp,
  xformers.ops.fmha.flash3.BwOp])

In [1]:
import flash_attn

flash_attn.__version__

'2.7.4.post1'

In [2]:
torch.__version__

'2.7.0+cu126'

In [ ]:
import torch
import torch._dynamo.backends.

# https://docs.pytorch.org/docs/stable/generated/torch.compile.html

# Normal and experimental torch compile backends
torch._dynamo.list_backends(), torch._dynamo.list_backends(None)


(['cudagraphs', 'inductor', 'onnxrt', 'openxla', 'tvm'],
 ['aot_eager',
  'aot_eager_decomp_partition',
  'aot_eager_decomp_partition_crossref',
  'aot_eager_decomp_partition_with_mode',
  'aot_eager_default_partitioner',
  'aot_ts',
  'cudagraphs',
  'dynamo_accuracy_minifier_backend',
  'dynamo_minifier_backend',
  'eager',
  'eager_debug',
  'eager_noexcept',
  'inductor',
  'non_leaf_compile_error_TESTING_ONLY',
  'onnxrt',
  'openxla',
  'openxla_eval',
  'pre_dispatch_eager',
  'relu_accuracy_error_TESTING_ONLY',
  'relu_compile_error_TESTING_ONLY',
  'relu_runtime_error_TESTING_ONLY',
  'ts',
  'tvm'])

In [11]:
# torch compile inductor backend
torch._inductor.list_mode_options(), torch._inductor.list_options()


({'default': {},
  'reduce-overhead': {'triton.cudagraphs': True},
  'max-autotune-no-cudagraphs': {'max_autotune': True,
   'coordinate_descent_tuning': True},
  'max-autotune': {'max_autotune': True,
   'triton.cudagraphs': True,
   'coordinate_descent_tuning': True}},
 ['TYPE_CHECKING',
  'inplace_padding',
  'can_inplace_pad_graph_input',
  'enable_auto_functionalized_v2',
  'debug',
  'disable_progress',
  'verbose_progress',
  'fx_graph_cache',
  'fx_graph_remote_cache',
  'bundle_triton_into_fx_graph_cache',
  'autotune_local_cache',
  'autotune_remote_cache',
  'bundled_autotune_remote_cache',
  'force_disable_caches',
  'sleep_sec_TESTING_ONLY',
  'custom_op_default_layout_constraint',
  'triton_kernel_default_layout_constraint',
  'cpp_wrapper',
  'online_softmax',
  'dce',
  'static_weight_shapes',
  'size_asserts',
  'nan_asserts',
  'scalar_asserts',
  'pick_loop_orders',
  'inplace_buffers',
  'allow_buffer_reuse',
  'memory_planning',
  'use_fast_math',
  'memory_pool',


In [ ]:
import xformers.ops as xops

xops.fmha.MemoryEfficientAttentionFlashAttentionOp

(xformers.ops.fmha.flash.FwOp, xformers.ops.fmha.flash.BwOp)